name: Build Benso.ch (Test)

on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out Tweets Repo
        uses: actions/checkout@v2
        with:
          repository: BensoGmbH/benso.chV2
          token: ${{ secrets.GH_SERVICE_ACCOUNT }}  

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '10.x'
      
      - name: Install dependencies
        run: npm install

      - name: Install gatsby-cli
        run: npm install -g gatsby-cli

      - name: Format Code
        run: npm run format

      - name: Build
        run: npm run build -- --prefix-paths
      
      - name: Publish
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: test
          FOLDER: public
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
